# Generated by Django 5.0.6 on 2024-06-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anilist', models.IntegerField(unique=True)),
                ('id_mal', models.IntegerField(unique=True)),
                ('romaji_title', models.CharField(max_length=150, unique=True)),
                ('english_title', models.CharField(max_length=150, unique=True)),
                ('native_title', models.CharField(max_length=150, unique=True)),
                ('format', models.CharField(choices=[('TV_SHORT', 'Tv Short')], max_length=10)),
                ('status', models.CharField(choices=[('RELEASING', 'Releasing')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('episodes', models.SmallIntegerField()),
                ('duration', models.SmallIntegerField()),
                ('source', models.CharField(choices=[('MANGA', 'Manga')], max_length=20)),
                ('hashtag', models.CharField(max_length=150)),
                ('trailer', models.CharField(max_length=150)),
                ('cover_img_large', models.CharField(max_length=150)),
                ('cover_img_med', models.CharField(max_length=150)),
                ('banner_img_large', models.CharField(max_length=150)),
                ('banner_img_med', models.CharField(max_length=150)),
                ('weighted_score', models.SmallIntegerField()),
                ('mean_score', models.SmallIntegerField()),
                ('popularity', models.IntegerField()),
                ('trending', models.BigIntegerField()),
                ('favorites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_native', models.CharField(max_length=150)),
                ('img_large', models.CharField(max_length=150)),
                ('img_med', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.TextField()),
                ('favorites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('icon', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_native', models.CharField(max_length=150)),
                ('img_large', models.CharField(max_length=150)),
                ('img_med', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('home_town', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('favorites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('is_general_spoiler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=150, unique=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, unique=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.externalsite')),
            ],
        ),
        migrations.CreateModel(
            name='StaffExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, unique=True)),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.externalsite')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffInAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(max_length=150)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staff')),
            ],
            options={
                'unique_together': {('anime_id', 'staff_id')},
            },
        ),
        migrations.CreateModel(
            name='AnimeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('PARENT', 'Parent')], max_length=15)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_id', to='base.anime')),
                ('senior_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_anime_id', to='base.anime')),
            ],
            options={
                'unique_together': {('anime_id', 'senior_anime_id')},
            },
        ),
        migrations.CreateModel(
            name='StaffVoiceCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_role', models.CharField(choices=[('SUPPORTING', 'Supporting')], max_length=10)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
                ('staff_in_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staffinanime')),
            ],
            options={
                'unique_together': {('char_id', 'staff_in_anime_id')},
            },
        ),
        migrations.CreateModel(
            name='AnimeProducedByStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
                ('studio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studio')),
            ],
            options={
                'unique_together': {('anime_id', 'studio_id')},
            },
        ),
        migrations.CreateModel(
            name='AnimeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(default=0)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tag')),
            ],
            options={
                'unique_together': {('anime_id', 'tag_id')},
            },
        ),
    ]
