# Generated by Django 5.0.6 on 2024-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.CharField(choices=[('TV', 'Tv'), ('TV_SHORT', 'Tv Short'), ('MOVIE', 'Movie'), ('SPECIAL', 'Special'), ('OVA', 'Ova'), ('ONA', 'Ona'), ('MUSIC', 'Music')], max_length=10),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('MANGA', 'Manga'), ('LIGHT_NOVEL', 'Light Novel'), ('VISUAL_NOVEL', 'Visual Novel'), ('VIDEO_GAME', 'Video Game'), ('OTHER', 'Other'), ('NOVEL', 'Novel'), ('DOUJINSHI', 'Doujinshi'), ('ANIME', 'Anime'), ('WEB_NOVEL', 'Web Novel'), ('LIVE_ACTION', 'Live Action'), ('GAME', 'Game'), ('COMIC', 'Comic'), ('MULTIMEDIA_PROJECT', 'Multimedia Project'), ('PICTURE_BOOK', 'Picture Book')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('RELEASING', 'Releasing'), ('NOT_YET_RELEASED', 'Not Yet Released'), ('CANCELLED', 'Cancelled'), ('HIATUS', 'Hiatus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animerelation',
            name='relation',
            field=models.CharField(choices=[('SEQUEL', 'Sequel'), ('PARENT', 'Parent'), ('SIDE_STORY', 'Side Story'), ('CHARACTER', 'Character'), ('SUMMARY', 'Summary'), ('SPIN_OFF', 'Spin Off'), ('OTHER', 'Other'), ('COMPILATION', 'Compilation'), ('CONTAINS', 'Contains')], max_length=15),
        ),
        migrations.AlterField(
            model_name='staffvoicecharacter',
            name='char_role',
            field=models.CharField(choices=[('MAIN', 'Main'), ('SUPPORTING', 'Supporting'), ('BACKGROUND', 'Background')], max_length=10),
        ),
    ]
